name: hogent_resto
description: Raadpleeg menu’s van verschillende Hogent resto’s.
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.4
  loader_overlay: ^2.0.7
  localstorage: ^4.0.0+1
  separated_column: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  adaptive_icon_background: '#ffffff'
  image_path: 'assets/icon.png'

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/splash.png'

flutter:
  uses-material-design: true

  assets:
    - icon.png
    - splash.png
    - ikke.jpeg
    - .env

  fonts:
    - family: hogent
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
